---
- hosts: localhost
  connection: local
  vars:
    - uuid: "{{ ansible_default_ipv4['macaddress'] | to_uuid }}"
  tasks:
    # Configure Shibboleth
    - name: install shibboleth
      become: yes
      remote_user: root
      apt: name=libapache2-mod-shib2
    - name: check shib key
      stat:
        path: /etc/shibboleth/sp-key.pem
      register: sp_key
    - name: generate shib key
      become: yes
      remote_user: root
      shell: shib-keygen
      when: sp_key.stat.exists == False
    - name: configure shibboleth
      become: yes
      remote_user: root
      vars:
        local_entity_id: "https://mysp.example.com/shibboleth/{{ uuid }}"
      template:
        src: ../templates/shibboleth2.xml.j2
        dest: /etc/shibboleth/shibboleth2.xml
      notify:
        - restart shibd
        - restart apache
    # Configure Keystone
    - name: configure keystone vhost
      become: yes
      remote_user: root
      blockinfile:
        path: /etc/apache2/sites-available/keystone.conf
        block: |
          <Location ~ "/identity/v3/auth/OS-FEDERATION/websso/mapped">
              AuthType shibboleth
              Require valid-user
              ShibRequestSetting requireSession 1
              ShibRequireSession On
              ShibExportAssertion Off
          </Location>
          <Location /Shibboleth.sso>
              SetHandler shib
          </Location>
          <Location /identity/v3/OS-FEDERATION/identity_providers/myidp/protocols/mapped/auth>
              ShibRequestSetting requireSession 1
              AuthType shibboleth
              ShibExportAssertion Off
              Require valid-user
          </Location>
          <Location ~ "/identity/v3/auth/OS-FEDERATION/identity_providers/myidp/protocols/mapped/websso">
              AuthType shibboleth
              Require valid-user
          </Location>
          WSGIScriptAliasMatch ^(/v3/OS-FEDERATION/identity_providers/.*?/protocols/.*?/auth)$ /usr/local/bin/keystone-wsgi-public/
      notify:
        - restart apache
    - name: set keystone remote_id_attribute
      ini_file:
        create: no
        dest: /etc/keystone/keystone.conf
        section: federation
        option: remote_id_attribute
        value: Shib-Identity-Provider
      notify:
        - restart apache
    - name: set keystone trusted_dashboard
      ini_file:
        create: no
        dest: /etc/keystone/keystone.conf
        section: federation
        option: trusted_dashboard
        value: "http://{{ ansible_default_ipv4['address'] }}/dashboard/auth/websso/"
      notify:
        - restart apache
    - name: turn on keystone insecure_debug
      ini_file:
        create: no
        dest: /etc/keystone/keystone.conf
        section: DEFAULT
        option: insecure_debug
        value: true
      notify:
        - restart apache
    - name: copy redirect template
      copy:
        src: /opt/stack/keystone/etc/sso_callback_template.html
        dest: /etc/keystone/sso_callback_template.html
    # Configure Horizon
    - name: set horizon WEBSSO_ENABLED
      lineinfile:
        create: no
        dest: /opt/stack/horizon/openstack_dashboard/local/local_settings.py
        regexp: '^#?WEBSSO_ENABLED ?=.*$'
        line: 'WEBSSO_ENABLED = True'
      notify:
        - restart apache
    - name: set horizon WEBSSO_ENABLED
      lineinfile:
        create: no
        dest: /opt/stack/horizon/openstack_dashboard/local/local_settings.py
        regexp: '^#?WEBSSO_CHOICES ?= ?\(.*$'
        line: 'WEBSSO_CHOICES = (("credentials", _("Keystone Credentials")), ("mapped", _("Security Assertion Markup Language")),)'
      notify:
        - restart apache
    # Refresh apache and shibd so that keystone and shibboleth are in working order before trying to use them
    - meta: flush_handlers
    # Create federated resources
    - name: install shade
      pip:
        name: shade
      become: yes
      remote_user: root
    - name: create federated domain
      os_keystone_domain: name=federated_domain
      register: domain
    - name: create federated project
      os_project: name=federated_project domain_id="{{ domain.id }}"
    - name: create federated group
      os_group: name=federated_users domain_id="{{ domain.id }}"
    - name: add federated users to federated domain
      os_user_role:
        group: 'federated_users'
        domain: "{{ domain.id }}"
        role: 'Member'
    - name: add federated users to federated project
      os_user_role:
        group: federated_users
        project: federated_project
        role: Member
    - name: check existence of identity provider
      shell: openstack identity provider show myidp
      ignore_errors: True
      changed_when: False
      register: check_idp
    - name: create identity provider
      shell: openstack identity provider create --remote-id https://idp.testshib.org/idp/shibboleth myidp
      when: check_idp|failed
    - name: define mapping rules
      template:
        dest: /opt/stack/rules.json
        src: ../templates/rules.json.j2
      register: define_mapping
    - name: check existence of mapping
      shell: openstack mapping show myidp_mapping
      ignore_errors: True
      changed_when: False
      register: check_mapping
    - name: create mapping
      shell: openstack mapping create --rules /opt/stack/rules.json myidp_mapping
      when: check_mapping|failed
    - name: update mapping
      shell: openstack mapping set --rules /opt/stack/rules.json myidp_mapping
      when: define_mapping['changed']
    - name: check existence of federation protocol
      shell: openstack federation protocol show mapped --identity-provider=myidp
      ignore_errors: True
      changed_when: False
      register: check_protocol
    - name: create federation protocol
      shell: openstack federation protocol create mapped --mapping myidp_mapping --identity-provider myidp
      when: check_protocol|failed
    # Register on testshib
    - name: download metadata
      get_url:
        url: "http://{{ ansible_default_ipv4['address'] }}/Shibboleth.sso/Metadata"
        dest: "{{ ansible_env['HOME'] }}/mysp.example.com.{{ uuid }}.xml"
      register: metadata
    - name: register on testshib
      # The URI module doesn't have an equivalent of -F to post files
      shell: "curl -X POST -F \"userfile=@{{ ansible_env['HOME'] }}/mysp.example.com.{{ uuid }}.xml\" https://www.testshib.org/procupload.php"
      args:
        warn: no
      when: metadata['changed']
  handlers:
    - name: restart shibd
      become: yes
      remote_user: root
      service: name=shibd state=restarted
    - name: restart apache
      become: yes
      remote_user: root
      service: name=apache2 state=restarted
