---
- hosts: localhost
  connection: local
  vars:
    - devstack_path: "{{ ansible_env['HOME'] }}/devstack"
  tasks:
    - name: download devstack
      git:
        repo: git://git.openstack.org/openstack-dev/devstack
        dest: "{{ devstack_path }}"
    - name: copy local.conf
      copy:
        src: "{{ devstack_path }}/samples/local.conf"
        dest: "{{ devstack_path }}/local.conf"
    - name: configure enabled services
      lineinfile:
        create: no
        dest: "{{ devstack_path }}/local.conf"
        line: "ENABLED_SERVICES=mysql,rabbit,key,horizon"
    - name: check devstack
      become: yes
      remote_user: root
      shell: "systemctl status devstack@keystone.service"
      register: devstack_started
      ignore_errors: True
      changed_when: False
    - name: run devstack
      command: "{{ ansible_env['HOME'] }}/devstack/stack.sh"
      when: devstack_started|failed
